"use strict";
let bookTitle = "TypeScript Basics";
const libraryName = "My Library";
let numberOfBooks = 25;
let isLibraryOpen = true;
let titulo;
let autor;
let genero;
let idioma;
let precio;
let formato;
let isbn;
let descripcion;
let estado;
let ubicacion;
let fecha_publicacion;
let editorial;
let paginas;
let dimensiones;
let peso;
let disponible;
titulo = "El Principito";
autor = "Antoine de Saint-Exupéry";
genero = "Novela corta, cuento filosófico";
idioma = "Español";
precio = 29.99;
formato = "Físico";
isbn = "9789580009948";
descripcion = "Un piloto se encuentra varado en el desierto del Sahara después de que su avión sufriera una avería, pero ahí conoce a un pequeño príncipe proveniente de otro planeta.",
    estado = "Nuevo";
ubicacion = "Colombia";
fecha_publicacion = new Date("2000-06-01");
editorial = "Torre de papel";
paginas = 320;
dimensiones = 22 + "x" + 14 + "cm";
peso = 500 + "g";
disponible = true;
